// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkrDf02Ktb1l4rQN9f5KCeY661j1H1A8',
    appId: '1:201074102687:web:202e9cada32a85152fadaa',
    messagingSenderId: '201074102687',
    projectId: 'workout-tracker-javelin',
    authDomain: 'workout-tracker-javelin.firebaseapp.com',
    storageBucket: 'workout-tracker-javelin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9an4iG0Kk3AFIiS8uJi_rXBgGFJJ3ic',
    appId: '1:201074102687:android:0223f460f7e10fc72fadaa',
    messagingSenderId: '201074102687',
    projectId: 'workout-tracker-javelin',
    storageBucket: 'workout-tracker-javelin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_K7QIkjTsw-vFozCtzoKQxxtiXj-oqoY',
    appId: '1:201074102687:ios:aabdcecc76eb4a452fadaa',
    messagingSenderId: '201074102687',
    projectId: 'workout-tracker-javelin',
    storageBucket: 'workout-tracker-javelin.appspot.com',
    iosClientId: '201074102687-end4q5ul0m08vpquvi11d7l8vtajkvrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.javelinWorkoutTracker',
  );
}
